name: rbc
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - cudatoolkit=11.3.1
  - h5py=3.6.0
  - hdf5=1.10.6
  - ipykernel=6.9.1
  - ipython=8.3.0
  - jupyter_client=7.2.2
  - jupyter_core=4.10.0
  - matplotlib=3.5.1
  - numpy=1.21.5
  - pandas=1.4.2
  - pip=21.2.4
  - pytorch=1.11.0
  - tqdm=4.64.0
  - gym
  - stable-baselines3
  - zipp
  - pip:
    - chess==1.9.2
    - reconchess==1.6.9
    - scikit-learn==1.1.1
    - scipy==1.8.1
    - ipywidgets 
    - widgetsnbextension 
    - pandas-profiling
    - rtpt
    - torchgeometry
